services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./database:/app/database
      - ./coverage-report:/var/www/html/coverage-report
    depends_on:
      - mailpit
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
